stages:
  - test

variables:
  FORTIFY_ROOT: /opt/Fortify/Fortify_SCA_23.2.0/bin

test:
  stage: test
  image: mcr.microsoft.com/dotnet/aspnet
  script:
    - echo "Running tests"
    - $FORTIFY_ROOT/sourceanalyzer -b "test" -clean
    # - $FORTIFY_ROOT/sourceanalyzer -b "test" dotnet build .\Owasp2021Top10\
    - $FORTIFY_ROOT/sourceanalyzer -b "test" .
    - $FORTIFY_ROOT/sourceanalyzer -b "test" -Xmx4G -Xss24m -Xms512m -debug -verbose -scan -f "test.fpr"
    - $FORTIFY_ROOT/sourceanalyzer -b "test" -show-files
    - $FORTIFY_ROOT/ReportGenerator -format pdf -f "test.pdf" "test.fpr"
  artifacts:
    paths:
      - "test.fpr"
      - "test.pdf"
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
  tags:
    - docker
    