version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: owasp_intern
      MYSQL_USER: application
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
